# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d47db70b563c2bfafb4745bac74ff42da3a54fa33c3310ae2ea8cef2477dd0afb402402b60e0d0ad82a83e65237f34f3553261ffb45abfcaf67723067c2b6a45

test:
  secret_key_base: 9709915ed78e0c2f03abe496a96752e07be98d12136b52901dc564fbbd78f9da1ee0a9943b7b1c2da3b757a9572777d792ead797b8846f5c97b5e219802ccf73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
